### ISSUE TITLE
Submodule replacement

### ISSUE THREAD

**Issue by hardikdava** [yzslab/gaussian-splatting-lightning#1]
@yzslab First of all great work, you have released the core codebase as MIT since submodule is private licensed. What do you think about using [gsplat](https://github.com/nerfstudio-project/gsplat) instead of inria based rendering submodule?

**Comment by yzslab** [comment]
Hi, thanks for your advice. I will take a look.

**Comment by yzslab** [comment]
> @yzslab any update on this issue? Thanks

Sorry for keeping you waiting. I am busy in doing other experiments, so this has not been scheduled yet.

**Comment by yzslab** [comment]
nerfstudio-project/gsplat has been integrated.

**Comment by hardikdava** [comment]
@yzslab I dont see it in main branch. Is it implemented in other branch?

**Comment by yzslab** [comment]
> > @yzslab I dont see it in main branch. Is it implemented in other branch?
> 
> I didn't add it to submodules. Install it via pip `pip install gsplat==0.1.8`, then use with `configs/gsplat.yaml`:
> 
> ```shell
> python main.py fit \
>     --config configs/gsplat.yaml \
>     ...
> ```

Besides, you need to make sure that `nvcc` is executable, or gsplat will be disabled.
gsplat should work if you can see output from command `which nvcc`:
```bash
$ which nvcc
/usr/local/cuda-11.8/bin/nvcc
```

**Comment by hardikdava** [comment]
Thanks @yzslab for great work.
