### ISSUE TITLE
killed in save ply

### ISSUE THREAD

**Issue by ansj11** [yzslab/gaussian-splatting-lightning#13]
your work is brilliant, but i run the code and killed in save ply: elements[:] = list(map(tuple, attributes)), do u know the reason? thanks in advance.
`        elements = np.empty(xyz.shape[0], dtype=dtype_full)
        attributes = np.concatenate((xyz, normals, f_dc, f_rest, opacities, scale, rotation), axis=1)
        set_trace()
        elements[:] = list(map(tuple, attributes))
        el = PlyElement.describe(elements, 'vertex')
        PlyData([el]).write(path)
        print('*'*20, '55555')`

**Comment by yzslab** [comment]
Looks like it was killed by OOM, how much RAM do you have? Did it happened during training?

**Comment by yzslab** [comment]
Try to use a machine with larger RAM, or increase the swap size.
If your are using images with large resolution, you can also smaller them to reduce RAM usage.

**Comment by ansj11** [comment]
thanks for your reply, I can training correctly.
