### ISSUE TITLE
Export Video

### ISSUE THREAD

**Issue by luoxue-star** [yzslab/gaussian-splatting-lightning#15]
How can I export the rendered video after completing the training using the official implementation?
Is it possible to generate an image from a specific viewpoint along with the corresponding camera parameters? If so, how does it work?

**Comment by yzslab** [comment]
Hi, the web viewer support the training output of the official implementation. The README contains the command to start the viewer.
In the `render` tab of the web viewer, you can build your own camera trajectory, and get the command that using to the export video.

**Comment by luoxue-star** [comment]
Thank you for your reply!
