### ISSUE TITLE
Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by LDYang694** [yzslab/gaussian-splatting-lightning#16]
when i run `python viewer.py ./4DGaussians/output/dnerf/bouncingballs/ --vanilla_gs4d`
it raise error 
RuntimeError: Error(s) in loading state_dict for deform_network:
        Unexpected key(s) in state_dict: "deformation_net.shs_deform.1.weight", "deformation_net.shs_deform.1.bias", "deformation_net.shs_deform.3.weight", "deformation_net.shs_deform.3.bias". 
I don't change any code in gs4d or this repo, how can I fix this error?

**Comment by rongakushin** [comment]
Hi, I'm encountering the same problem. Could you share how you resolved it? Thanks!

**Comment by muximuxi** [comment]
Have you solved the problem ？and when python viewer.py ./4DGaussians/output/dnerf/bouncingballs/point_cloud --vanilla_gs4d , error:
AssertionError: not a checkpoint or point cloud can be found.

**Comment by Coscatter** [comment]
> when i run `python viewer.py ./4DGaussians/output/dnerf/bouncingballs/ --vanilla_gs4d` it raise error RuntimeError: Error(s) in loading state_dict for deform_network: Unexpected key(s) in state_dict: "deformation_net.shs_deform.1.weight", "deformation_net.shs_deform.1.bias", "deformation_net.shs_deform.3.weight", "deformation_net.shs_deform.3.bias". I don't change any code in gs4d or this repo, how can I fix this error?

@LDYang694 Sadly, I encountered the same error, so have you solved the problem? I hope to get a response on how you solved it. Thank you very much.

**Comment by yzslab** [comment]
> > when i run `python viewer.py ./4DGaussians/output/dnerf/bouncingballs/ --vanilla_gs4d` it raise error RuntimeError: Error(s) in loading state_dict for deform_network: Unexpected key(s) in state_dict: "deformation_net.shs_deform.1.weight", "deformation_net.shs_deform.1.bias", "deformation_net.shs_deform.3.weight", "deformation_net.shs_deform.3.bias". I don't change any code in gs4d or this repo, how can I fix this error?
> 
> @LDYang694 Sadly, I encountered the same error, so have you solved the problem? I hope to get a response on how you solved it. Thank you very much.

Pull the latest version, it should work now.
