### ISSUE TITLE
fail to install requirements-second (CUDA)

### ISSUE THREAD

**Issue by antoinebio** [yzslab/gaussian-splatting-lightning#2]
Hello
i am not sure what it's going wrong during the installation of Gaussian Splatting Lightning

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/f6f2c658-2b2a-4ba7-afb3-05583499b248)

test with CUDA toolkit 11.8

console returns  a conflict with that toolkit ?

more precisely with

./submodules/tiny-cuda-nn-fp32/bindings/torch

**Comment by yzslab** [comment]
Hi, I haven't test this repository on Windows.
The tiny-cuda-nn should be able to detect the GPU architecture automatically. The `requirements-first.txt` may install the PyTorch with cuda 11.7 by default. If you are using cuda 11.8, try to install the PyTorch with cuda 11.8 manually: `pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118`, then run `pip install -r requirements-second.txt` again.

If the error persists, you need to set the environment `TCNN_CUDA_ARCHITECTURES` as the error mentioned.
Below are some possible values:
| H100 | 40X0 | 30X0 | A100 | 20X0 |
|:----:|:----:|:----:|:----:|:----:|
|   90 |   89 |   86 |   80 |   75 |

**Comment by yzslab** [comment]
If you only need the web viewer, or doesn't need appearance variation image support, it should works without tiny-cuda-nn installed.

**Comment by antoinebio** [comment]
Hi @yzslab 
thanks for the prompt reply.
unfortunately same issue with the recommended workaround

manual installation of the PyTorch with cuda 11.8 : pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118, 


![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/d3e7839c-ccc7-4aa9-801d-7004dc90748d)


then run pip install -r requirements-second.txt again.


![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/7ca1defe-5c34-4d35-8f03-1ac4da00d374)

**Comment by yzslab** [comment]
> Hi @yzslab thanks for the prompt reply. unfortunately same issue with the recommended workaround
> 
> manual installation of the PyTorch with cuda 11.8 : pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118,
> 
> ![image](https://user-images.githubusercontent.com/30265851/282092858-d3e7839c-ccc7-4aa9-801d-7004dc90748d.png)
> 
> then run pip install -r requirements-second.txt again.
> 
> ![image](https://user-images.githubusercontent.com/30265851/282093164-7ca1defe-5c34-4d35-8f03-1ac4da00d374.png)

You need to set the value of `TCNN_CUDA_ARCHITECTURES` correspond to your GPU (via `set TCNN_CUDA_ARCHITECTURES=...`) before running `pip install ...`.

**Comment by antoinebio** [comment]
ok I see.
but how could I force that argument ? and where ?
... in the conda console ?
or should I do that from sources files

<img width="544" alt="image" src="https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/2f693914-a434-4a75-b33c-a483127e63f4">

I am working with RTX4090 so i should use (set TCNN_CUDA_ARCHITECTURES=89)

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/62f66f44-a1ea-4414-b2b2-db9cba7367c8)

**Comment by yzslab** [comment]
> ok I see. but how could I force that argument ? and where ? ... in the conda console ? or should I do that from sources files
> 
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/30265851/282103697-2f693914-a434-4a75-b33c-a483127e63f4.png">
> I am working with RTX4090 so i should use (set TCNN_CUDA_ARCHITECTURES=89)
> 
> ![image](https://user-images.githubusercontent.com/30265851/282103990-62f66f44-a1ea-4414-b2b2-db9cba7367c8.png)

Try to run the `set TCNN_CUDA_ARCHITECTURES=89` on the console.

**Comment by antoinebio** [comment]
still ....

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/17f85e27-e725-41dc-a5b4-2512c73ff39d)

**Comment by yzslab** [comment]
> still ....
> 
> ![image](https://user-images.githubusercontent.com/30265851/282110801-17f85e27-e725-41dc-a5b4-2512c73ff39d.png)

Or try to set this enviroment variable in the Windows system property setting, then reopen the console.
![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/564361/84514525-0479-4628-b4bc-ad876eef9ea8)

**Comment by antoinebio** [comment]
I think I am all set ?

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/cf77a9dd-70aa-4942-b43d-2a4398c03393)

**Comment by yzslab** [comment]
> I think I am all set ?
> 
> ![image](https://user-images.githubusercontent.com/30265851/282115788-cf77a9dd-70aa-4942-b43d-2a4398c03393.png)

Like this:
![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/564361/3f149ce8-004e-4a62-91e1-deceb4402954)


Remember reopen the console after saving the settings.

**Comment by yzslab** [comment]
Or just remove the last line of the `requirements-second.txt` then run `pip install -r requirements-second.txt` again. The web viewer should works without tiny-cuda-nn.

**Comment by yzslab** [comment]
Please pull the latest version, it should works without tiny-cuda-nn now. It just an optional library, unless you need the appearance variation image support.

**Comment by antoinebio** [comment]
I tried to force the TCNN_CUDA_ARCHITECTURES variables but it leads to more unconsistent issues...

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/4c5d9209-db72-44a8-a8cb-5973b33d4b2a)


will try with the last version you uploaded.

**Comment by yzslab** [comment]
> I tried to force the TCNN_CUDA_ARCHITECTURES variables but it leads to more unconsistent issues...
> 
> ![image](https://user-images.githubusercontent.com/30265851/282119683-4c5d9209-db72-44a8-a8cb-5973b33d4b2a.png)
> 
> will try with the last version you uploaded.

Looks like some files are missing, you can try again after running below commands:
```bash
git submodule sync --recursive
git submodule update --init --recursive --force
```

**Comment by antoinebio** [comment]
even after starting from scratch with the last version I've got issue on that second step with requirements...

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/0adb8e14-4167-4051-9d6e-215f30d2c22b)

**Comment by yzslab** [comment]
> even after starting from scratch with the last version I've got issue on that second step with requirements...
> 
> ![image](https://user-images.githubusercontent.com/30265851/282125247-0adb8e14-4167-4051-9d6e-215f30d2c22b.png)

Please run `git pull` again, I removed tiny-cuda-nn from the `requirements-second.txt`.

**Comment by antoinebio** [comment]
ok I will test another time... but I manually remove that line in requirements-second.txt 

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/478f9972-5ac6-4fa2-929b-c0ff0eb47ebc)


and issue is still present...

Processing c:\gaussian-splatting-lightning\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\gaussian-splatting-lightning\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff-gaussian-rasterization, simple-knn
  Building wheel for diff-gaussian-rasterization (setup.py): started
  Building wheel for diff-gaussian-rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff-gaussian-rasterization
  Building wheel for simple-knn (setup.py): started
  Building wheel for simple-knn (setup.py): finished with status 'error'
  Running setup.py clean for simple-knn
Failed to build diff-gaussian-rasterization simple-knn

**Comment by antoinebio** [comment]
@yzslab  I remove my env and started the installation from scratch into conda

there I am
no issue at all !
![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/c7aea59d-0fed-4108-a391-99bedd355e0a)
