### ISSUE TITLE
Is there any instruction to download the blender dataset?

### ISSUE THREAD

**Issue by Boltzmachine** [yzslab/gaussian-splatting-lightning#20]
Sorry I am new to 3DGS. Just wonder where I can download it and do I need to do some preprocessings?

**Comment by yzslab** [comment]
Hi, you can download it here: https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1.
No preprocessing is needed.

**Comment by yzslab** [comment]
> Hi, you can download it here: https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1. No preprocessing is needed.

The `nerf_synthetic` directory contains the blender dataset.
