### ISSUE TITLE
Question about viewers

### ISSUE THREAD

**Issue by benjamin3344** [yzslab/gaussian-splatting-lightning#21]
Hi! If I have the viewer running on a CentOS cluster, can I change the host address in viewer.py and forward it to a laptop using ssh?

**Comment by yzslab** [comment]
Hi, you can change it by option '--host', e.g.: 'python viewer.py --host
YOU_EXPECTED_ADDRESS ...'. It is '0.0.0.0' by default. I think you do not
need to change it.

**Comment by Yuhuoo** [comment]
Hi, I connected my Mac laptop to an Ubuntu server using SSH. Then I ran viewer.py on the server, but when I tried to access the webpage on my local machine, it didn't render properly. Could you please tell me what I should do?

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/91204817/a39a124b-17f0-49f6-8a43-7c5bb02ccf70)

**Comment by yzslab** [comment]
> Hi, I connected my Mac laptop to an Ubuntu server using SSH. Then I ran viewer.py on the server, but when I tried to access the webpage on my local machine, it didn't render properly. Could you please tell me what I should do?
> 
> ![image](https://private-user-images.githubusercontent.com/91204817/320193008-a39a124b-17f0-49f6-8a43-7c5bb02ccf70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTI5NDAsIm5iZiI6MTcxMjM5MjY0MCwicGF0aCI6Ii85MTIwNDgxNy8zMjAxOTMwMDgtYTM5YTEyNGItMTdmMC00OWY2LThhNDMtN2M1YmIwMmNjZjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA4MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDAxZTE4ODI3MWI1YzU1YzJmNGM2YmI1YzM1OTQxZWYzYzY3NmRiMGY0OWI3MWQ5YmMyN2Y0ZjA2OWIwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEXxKDC6MARZbPzdNG4_yAghtl07boM3VdGwhSjXzR4)

Try to use SSH local forwarding, e.g.: 
```bash
ssh -L 8580:127.0.0.1:8580 YOU_USERNAME@YOUR_SERVER_ADDRESS
```
Then access `http://127.0.0.1:8580` on your browser.

**Comment by Yuhuoo** [comment]
> > Hi, I connected my Mac laptop to an Ubuntu server using SSH. Then I ran viewer.py on the server, but when I tried to access the webpage on my local machine, it didn't render properly. Could you please tell me what I should do?
> > ![image](https://private-user-images.githubusercontent.com/91204817/320193008-a39a124b-17f0-49f6-8a43-7c5bb02ccf70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTI5NDAsIm5iZiI6MTcxMjM5MjY0MCwicGF0aCI6Ii85MTIwNDgxNy8zMjAxOTMwMDgtYTM5YTEyNGItMTdmMC00OWY2LThhNDMtN2M1YmIwMmNjZjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA4MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDAxZTE4ODI3MWI1YzU1YzJmNGM2YmI1YzM1OTQxZWYzYzY3NmRiMGY0OWI3MWQ5YmMyN2Y0ZjA2OWIwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEXxKDC6MARZbPzdNG4_yAghtl07boM3VdGwhSjXzR4)
> 
> Try to use SSH local forwarding, e.g.:
> 
> ```shell
> ssh -L 8580:127.0.0.1:8580 YOU_USERNAME@YOUR_SERVER_ADDRESS
> ```
> 
> Then access `http://127.0.0.1:8580` on your browser.

Thanks for your reply, but it doesn't work.
![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/91204817/c758f88b-7b0e-4fe9-86d4-6625bc262ce5)

**Comment by yzslab** [comment]
Hi, start the viewer without the '--host ...' option then try again.

**Comment by Yuhuoo** [comment]
Thanks. I can render the scene successfully now. But how  to export the video?

**Comment by yzslab** [comment]
> Thanks. I can render the scene successfully now. But how to export the video?

Add keyframes in the `Render` panel of the web viewer, then click the `Generate Command` button. Copy the generated command and run it on your server.
