### ISSUE TITLE
How to load camear_path?

### ISSUE THREAD

**Issue by ch1998** [yzslab/gaussian-splatting-lightning#22]
How to load camera trajectories (colmap/json files) of training data and create rendering paths in the web?

**Comment by ch1998** [comment]
> Hi, start the viewer with option `--show-cameras` can load camera poses of training data. The rendering paths can be created in the `render` panel of the web viewer.

Thanks for the reply, the --show-cameras parameter seems to only display the red camera frame. I need to manually add keyframe to create the render path, is that right?

**Comment by yzslab** [comment]
Right!
