### ISSUE TITLE
Question of using viser.

### ISSUE THREAD

**Issue by Yuhuoo** [yzslab/gaussian-splatting-lightning#25]
Hi, I meet a strange behavior when rendering scenes with Viser. The camera is shaking, and I can't accurately control the direction. Moreover, when moving, it renders normally, but when I'm static, it suddenly returns to the last place it stopped.

<img width="1004" alt="image" src="https://github.com/yzslab/gaussian-splatting-lightning/assets/91204817/507b66ad-1680-48f1-ace1-66e0b39be940">
<img width="1137" alt="image" src="https://github.com/yzslab/gaussian-splatting-lightning/assets/91204817/eb6d6b7d-5590-4d95-a45d-bf45ac9ced51">

**Comment by yzslab** [comment]
Hi, try to start the viewer with option `--reorient disable`, and see whether the same problem exists.

**Comment by Yuhuoo** [comment]
Thank you, it works.

But I have another question. I want the camera to move around the target, but I can't control it accurately. The path isn't very circular, and the camera moves fast and not smoothly.

<img width="1394" alt="image" src="https://github.com/yzslab/gaussian-splatting-lightning/assets/91204817/0ee58f89-6590-4deb-ac8a-97938ebd160d">

**Comment by yzslab** [comment]
> Thank you, it works.
> 
> But I have another question. I want the camera to move around the target, but I can't control it accurately. The path isn't very circular, and the camera moves fast and not smoothly.
> 
> <img alt="image" width="1394" src="https://private-user-images.githubusercontent.com/91204817/325591073-0ee58f89-6590-4deb-ac8a-97938ebd160d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDkwMTIsIm5iZiI6MTcxNDA0ODcxMiwicGF0aCI6Ii85MTIwNDgxNy8zMjU1OTEwNzMtMGVlNThmODktNjU5MC00ZGViLWFjOGEtOTc5MzhlYmQxNjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEyMzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZGNiMWIzNGY2ZmVlNzRjZDk2M2Q4ZTQyOTllYzBmYTUxMmYwYzBjNjQ5ZWVlYzY5MThkMWJjMDNmNGQwMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wM8hgXEXkaAwYKTnON1jp7WfdCwl1C9Y52Bwj1G1_F0">

Rolling the wheel of your mouse forward to get maximum zoom in, it may be beneficial for you to control the camera accurately. You also need to use W/A/S/D keys to move camera in this state.

Besides, you can enable `Move keyframes` in the Render panel to move your keyframes, and make it more circular.

**Comment by Yuhuoo** [comment]
Thank you for your response. I'd like to ask how I can set the custom initial camera pose for the scene.

**Comment by yzslab** [comment]
> Thank you for your response. I'd like to ask how I can set the custom initial camera pose for the scene.

Do you mean the initial camera pose for the web viewer? Not implemented yet. You can add your code to set it by updating `client.camera.wxyz` and `client.camera.wxyz`, e.g.: https://github.com/yzslab/gaussian-splatting-lightning/blob/a23ad2ebac5cf6d182ab48d110122f67f2e132ee/viewer.py#L224-L225

**Comment by yzslab** [comment]
> Otherwise, how do I control pitch, roll, and yaw angles? When I set the up_direction, their behavior is incorrect.

Controlling these values directly has not been implemented yet neither.

**Comment by Yuhuoo** [comment]
> > Otherwise, how do I control pitch, roll, and yaw angles? When I set the up_direction, their behavior is incorrect.
> 
> Controlling these values directly has not been implemented yet.

Sure! Here's the translation:

OK! Thank you so much. Could you leave your email? I'd like to make a friend with you.

**Comment by yzslab** [comment]
> > > Otherwise, how do I control pitch, roll, and yaw angles? When I set the up_direction, their behavior is incorrect.
> > 
> > 
> > Controlling these values directly has not been implemented yet.
> 
> OK! Thank you so much. Could you leave your email? I'd like to make a friend with you.

Glad to hear that: 07_ukulele.canters@icloud.com

**Comment by Yuhuoo** [comment]
Can you tell me how to add roll angle cotrolling code? I urgently need it.

**Comment by yzslab** [comment]
> Could you tell me how to add roll angle cotrolling code? I urgently need it.

First convet your angle to quaternion (wxyz), then multiply with `camera.wxyz`, and update it with the result.
The conversion and multiplication can be done with `viser.transforms.SO3`: https://viser.studio/transforms/#viser.transforms.SO3
