### ISSUE TITLE
Rotation of Spherical harmonics data

### ISSUE THREAD

**Issue by hardikdava** [yzslab/gaussian-splatting-lightning#26]
Great work @yzslab , is it possible to add support for rotation and scalling of  spherical harmonics data with the transformation of 3dgs model?

**Comment by yzslab** [comment]
Sorry that not planning yet. Contributions are welcomed!

**Comment by yzslab** [comment]
Rotate the first extra degree has been implemented.
The calculation of the higher SH degrees are far more tedious, so only one degree currently.

**Comment by hardikdava** [comment]
@yzslab thanks a lot. Can you give me the direction how to achieve the rotation for 3 sh degree? I would like to try it out.

**Comment by yzslab** [comment]
> @yzslab thanks a lot. Can you give me the direction how to achieve the rotation for 3 sh degree? I would like to try it out.

Already provided in the code comment: https://github.com/yzslab/gaussian-splatting-lightning/blob/020c21c98d186f0e85c19355eab9db0e80d1f085/utils/gaussian_transform.py#L87-L97

**Comment by hardikdava** [comment]
@yzslab It's not possible to rotate higher degree of spherical harmonics without knowing camera matrix. Am I right? 

P.S. I want to do it offline. `Trained model -> rotate -> visualize`

**Comment by yzslab** [comment]
> @yzslab It's not possible to rotate higher degree of spherical harmonics without knowing camera matrix. Am I right?
> 
> P.S. I want to do it offline. `Trained model -> rotate -> visualize`

The camera matrix isn't required. The `R` is the matrix that rotate your scene.

**Comment by hardikdava** [comment]
@yzslab I tried your implementation and it's working perfect for 1st degree. But still missing implementation for 2nd and higher degree.

**Comment by yzslab** [comment]
> @yzslab I tried your implementation and it's working perfect for 1st degree. But still missing implementation for 2nd and higher degree.

The calculation of the higher SH degrees are far more tedious.
But rotating the view direction vectors are more easier: `R.T @ (means3D' - camera_center)`. I think you can modifying the rasterizer to get correct colors by this way.

**Comment by yzslab** [comment]
> > @yzslab I tried your implementation and it's working perfect for 1st degree. But still missing implementation for 2nd and higher degree.
> 
> The calculation of the higher SH degrees are far more tedious. But rotating the view direction vectors are more easier: `R.T @ (means3D' - camera_center)`. I think you can modifying the rasterizer to get correct colors by this way.

Just need to modify the rasterizer to accept a rotation matrix `R` as a parameter, and apply it when calculating colors.

**Comment by hardikdava** [comment]
@yzslab I think there is an error with your formula. It will create dim mismatch error. Can you recheck it once?

**Comment by yzslab** [comment]
> @yzslab I think there is an error with your formula. It will create dim mismatch error. Can you recheck it once?

Would you mind providing more details?

**Comment by yzslab** [comment]
> > @yzslab I think there is an error with your formula. It will create dim mismatch error. Can you recheck it once?
> 
> Would you mind providing more details?

The `means3D' - camera_center` is a column vector.

**Comment by hardikdava** [comment]
@yzslab I am using modified version of `gsplat` rasterizer. I have rotated first degree as you implemented. I modified the color computation as you suggested and I am getting following error:

```
    viewdirs = camera.camera_to_worlds.detach()[..., :3, :3].T @ (means_crop.detach() - camera.camera_to_worlds.detach()[..., :3, 3])
RuntimeError: mat1 and mat2 shapes cannot be multiplied (9x1 and 82214x3)
```

**Comment by yzslab** [comment]
> @yzslab I am using modified version of `gsplat` rasterizer. I have rotated first degree as you implemented. I modified the color computation as you suggested and I am getting following error:
> 
> ```
>     viewdirs = camera.camera_to_worlds.detach()[..., :3, :3].T @ (means_crop.detach() - camera.camera_to_worlds.detach()[..., :3, 3])
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (9x1 and 82214x3)
> ```

The `means3D` and `camera_center` in Python code are row vectors. So the correct calculation in code should be: 
```
(means3D` - camera_center) @ R
```
NOTE:
  * No transpose/inverse is required for $R$ if placing on the right.
  * The `R` isn't the camera matrix, should be the one rotating your scene.

**Comment by yzslab** [comment]
> have rotated first degree

Besides, you should not rotate SHs and the view direction together. Rotation should be applied either for SHs or view directions.

**Comment by hardikdava** [comment]
@yzslab You are right. I got it working for applying Rotation directly to view direction. How can I achieve rotation without modifying the rasterizer? Is it possible?

**Comment by yzslab** [comment]
> How can I achieve rotation without modifying the rasterizer? Is it possible?

I think rotating the SHs is the only way achieve this.

**Comment by hardikdava** [comment]
@yzslab can you send me references on how can rotate SH for higher degree if you have it?

**Comment by yzslab** [comment]
> @yzslab can you send me references on how can rotate SH for higher degree if you have it?

I think the theory is the same as the 1st extra degree. Some one mentioned that it could be done with Wigner D-matrix: https://github.com/graphdeco-inria/gaussian-splatting/issues/176#issuecomment-1711876624
Here is a implementation: https://github.com/graphdeco-inria/gaussian-splatting/issues/176#issuecomment-2060513169
I don't know whether it is correct. The results of the 1st extra degree are differ to the calculation here.

**Comment by hardikdava** [comment]
@yzslab I tried the mentioned method. But It's not yielding good result.

**Comment by yzslab** [comment]
> @yzslab I tried the mentioned method. But It's not yielding good result.

Thanks to [MstXy](https://github.com/MstXy), this problem has been solved now: https://github.com/graphdeco-inria/gaussian-splatting/issues/176#issuecomment-2147223570
I validated that the latest one is correct.

**Comment by hardikdava** [comment]
@yzslab Thanks for the support. I have also verified the result.

**Comment by Golbstein** [comment]
It's not working for me for some reason though.

I have a gaussian model
and a transformation matrix R and t

I transform my xyz: 
means3D = (R @ means3D.T).T + t

then I find my new scale and new rotation in this way:

actual_covariance = L @ L.transpose(1, 2)
sigma_new = R @ actual_covariance @ R.T
new_scales, new_rotations = torch.linalg.eigh(sigma_new)
new_rotations = rotation_to_quaternion(new_rotations)

However, rotating the SH as mentioned in the issue in the original repo for some reason not yielding me the exact same rendered image as I would have expected (as I get for the untranslated gaussians) what could be the reason for it?
