### ISSUE TITLE
Question about 3DGS editing, add, removal? 

### ISSUE THREAD

**Issue by TurtleZhong** [yzslab/gaussian-splatting-lightning#27]
Hi, I found that this project has more functions than the original version. It seems that it can edit a single result and load multiple point cloud files for visualization; but I found that I cannot watch the video in the README file, so I would like to ask for advice, Can I use this project to remove dynamic objects from a scene and add new objects to the scene? And export the new scene. If possible, that would be really great.

**Comment by yzslab** [comment]
You can remove specific region of your scene, add new objects (must be a 3DGS reconstruction), and save the edited scene as ply or ckpt file.
