### ISSUE TITLE
viewer not working after training

### ISSUE THREAD

**Issue by antoinebio** [yzslab/gaussian-splatting-lightning#3]
Hi

after a first train I want to view the trained model

but python viewer.py script used like that
python .\viewer.py .\outputs\TEST01\
returns that issue below...

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/1494db7b-4004-4f2f-9456-81aea31518d2)

Is my train folder consitent ?

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/92ef386b-7923-440a-b273-86e6e0f68df9)

**Comment by yzslab** [comment]
As your image shown, the training was interrupted. Please try again after training finished.

**Comment by antoinebio** [comment]
@yzslab is it possible to limit the train to a limit value for good end of that step?

**Comment by yzslab** [comment]
> @yzslab is it possible to limit the train to a limit value for good end of that step?

By default, the training will stop at 30k iterations. You can change this value by `--max_steps` options.

**Comment by antoinebio** [comment]
unfortunately it's not working

end of iteration here

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/cde768fa-606d-4d1f-89ff-f688850da7ba)


and viewer launch...

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/1a2fca3e-a92c-4c11-82b4-008a81a6b440)

**Comment by yzslab** [comment]
> unfortunately it's not working
> 
> end of iteration here ( i set 100 iterations)
> 
> ![image](https://user-images.githubusercontent.com/30265851/282250513-cde768fa-606d-4d1f-89ff-f688850da7ba.png)
> 
> and viewer launch...
> 
> ![image](https://user-images.githubusercontent.com/30265851/282250488-1a2fca3e-a92c-4c11-82b4-008a81a6b440.png)


Run this:
```bash
pip uninstall viser
pip install viser==0.1.9
```

**Comment by antoinebio** [comment]
thanks that solved the last issue.

how does viser work ? the viewer part ?

should I install and use httpserver to emulate the server , or XAMPP ?

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/de6974d7-daff-47f9-8587-efd67e1ca507)

I tried the URL in a chrome browser without any 

should I use that nerfstrudio viewer instead ? 

https://viewer.nerf.studio/?websocket_url=ws://localhost:7007

**Comment by yzslab** [comment]
> thanks that solved the last issue.
> 
> how does viser work ? the viewer part ?
> 
> should I install and use httpserver to emulate the server , or XAMPP ?
> 
> ![image](https://user-images.githubusercontent.com/30265851/282289336-de6974d7-daff-47f9-8587-efd67e1ca507.png)
> 
> I tried the URL in a chrome browser without any
> 
> should I use that nerfstrudio viewer instead ?
> 
> https://viewer.nerf.studio/?websocket_url=ws://localhost:7007

Access: http://localhost:8080
