### ISSUE TITLE
Enable transform and edit in the viewer

### ISSUE THREAD

**Issue by carolinaicardi1** [yzslab/gaussian-splatting-lightning#30]
Hi, I would like to use my trained data from https://github.com/hustvl/4DGaussians in the viewer, but I only see the general panel and not the edit and render ones. What do I need to do to enable them? 

![web viewer](https://github.com/yzslab/gaussian-splatting-lightning/assets/115872783/1500a85b-1e91-4bd3-be93-b176e2b971ca)
![console output](https://github.com/yzslab/gaussian-splatting-lightning/assets/115872783/fbe49e52-610f-4441-a60f-0d1b49a33b94)

**Comment by yzslab** [comment]
Hi, edit and render are not compatible with third-partry dynamic scene.
If you really need it you can implemente it yourself.
