### ISSUE TITLE
What is depth unit?

### ISSUE THREAD

**Issue by tamuatamu** [yzslab/gaussian-splatting-lightning#33]
Sure, I can help with that. Here's a revised version of your text:

I want to ask about the depth unit we can get from a depth image.

I checked the inside of the depth image like below.
I want to know the depth value for each pixel.
But the image has 3 channels, and I'm not sure about the unit of measurement (meters or something else).
Could you please help me understand this?
Thank you.

`def get_outputs(self, camera, scaling_modifier: float = 1.):
    image = self.renderer(
        camera,
        self.gaussian_model,
        self.background_color,
        scaling_modifier=scaling_modifier,
        render_types=[self.render_type],
    )[self.output_key]
    image = self.output_processor(image)
    print(image)
    print(image.shape)
    if image.shape[0] == 1:
        image = image.repeat(3, 1, 1)
    return image`

**Comment by yzslab** [comment]
Hi, there is no unit for depth. It is the value of the z axis in camera space.
Please note that the `image` return by `self.output_processor()` is not depth value anymore. It is the colormap of the depth value.
