### ISSUE TITLE
viewer problem

### ISSUE THREAD

**Issue by Yuhuoo** [yzslab/gaussian-splatting-lightning#34]
How to slow down the camera movement when using viewer?

**Comment by yzslab** [comment]
It can not be changed directly currently. 
You need to clone the [viser](https://github.com/nerfstudio-project/viser), and change the `0.002`, which represent the speed of the camera, to the value you want here: [src/viser/client/src/CameraControls.tsx#L142-L159](https://github.com/nerfstudio-project/viser/blob/8d690da7a2cb467f4788cdcf38ccad5364e49f43/src/viser/client/src/CameraControls.tsx#L142-L159).
Then install your local modified version.
