### ISSUE TITLE
update instructions to the latest gsplat

### ISSUE THREAD

**Issue by czero69** [yzslab/gaussian-splatting-lightning#36]
Hey, could we please update to the latest gsplat=1.0.0 ?
 
the instruction in readme is now:
```pip install git+https://github.com/yzslab/gsplat.git```
but this is installing 0.1.12 version of gsplat whether the latests are 1.0.0, could get from
```pip install git+https://github.com/nerfstudio-project/gsplat.git```

**Comment by yzslab** [comment]
Hi, only `v0.1.12` is supported currently. I will upgrade to `v1` when they have the next release later.

**Comment by cs-mshah** [comment]
@yzslab 
There is a recent release (https://github.com/nerfstudio-project/gsplat/releases/tag/v1.3.0) which has some massive upgrades such as support for compression, orthographic projection.

**Comment by yzslab** [comment]
> @yzslab There is a recent release (https://github.com/nerfstudio-project/gsplat/releases/tag/v1.3.0) which has some massive upgrades such as support for compression, orthographic projection.

I noticed that, but I am busy doing experiments, so maybe later.

**Comment by hardikdava** [comment]
@yzslab @czero69 @cs-mshah I tried to update gsplat rasterizer version but directly usage of `rasterization` is not possible. All gradients are attached in `strategy` part. So no way to directly use like in older versions. 

Referance issue: https://github.com/nerfstudio-project/gsplat/issues/467

**Comment by yzslab** [comment]
> @yzslab @czero69 @cs-mshah I tried to update gsplat rasterizer version but directly usage of `rasterization` is not possible. All gradients are attached in `strategy` part. So no way to directly use like in older versions.
> 
> Referance issue: [nerfstudio-project/gsplat#467](https://github.com/nerfstudio-project/gsplat/issues/467)

Take a look this if you really need it: https://github.com/yzslab/gaussian-splatting-lightning/blob/gsplat_v1/internal/renderers/gsplat_v1_renderer.py

**Comment by yzslab** [comment]
Hi, sorry for keeping everyone waiting.

I have added the v0 interfaces to the latest gsplat v1 so it can work on this repo now: 
```bash
pip install git+https://github.com/yzslab/gsplat.git@v1-with_v0_interfaces
```
This just a workaround so v0 is still the recommended choice, unless you really need v1.

**Comment by hardikdava** [comment]
@yzslab Sorry to bother you again. I am trying to train appereance model with `gsplat_v1` branch with gsplat-v1 version. I am getting this error. I replaced `GSPlatRenderer` with `GSplatV1Renderer`. Can you help to fix this issue?

```
  File "/home/hd/Desktop/python_workspace/gaussian-splatting-lightning/internal/gaussian_splatting.py", line 241, in forward
    return self.renderer.training_forward(
  File "/home/hd/Desktop/python_workspace/gaussian-splatting-lightning/internal/renderers/gsplat_appearance_embedding_renderer.py", line 164, in training_forward
    return self.renderer(
TypeError: 'GSplatV1Renderer' object is not callable
```
Thanks

**Comment by yzslab** [comment]
> I replaced `GSPlatRenderer` with `GSplatV1Renderer`. Can you help to fix this issue?

You need to invoke the `instantiate()` interface of the `GSplatV1Renderer`, and then assign its return value to `self.renderer`.
It means that in `GSplatAppearanceEmbeddingRenderer`'s `setup()`, there should be `self.renderer = GSplatV1Renderer().instantiate()`.

**Comment by yzslab** [comment]
Closing the issue now as there are already renderers fully utilizing the gsplat v1 interfaces.
