### ISSUE TITLE
Some of the demo videos are not accessible

### ISSUE THREAD

**Issue by GopiRajuMatta** [yzslab/gaussian-splatting-lightning#39]
Hello @yzslab!

Thank you for sharing very useful repository.

Some of the demo videos are not accessible like Transform.mp4, Edit.mp4. 

Can you please check once and update. I want to do some editing like removing some gaussians, part of the point cloud etc, not sure how to do the same. Hope those demo videos mentioned above would be useful..

Thank you
Gopi

**Comment by yzslab** [comment]
Hi, some videos are h.265 encoded. What OS and browser are you using?

**Comment by yzslab** [comment]
Here are two new videos:

https://github.com/user-attachments/assets/19770cd3-3627-45ba-9195-9f8d4ca19c21

https://github.com/user-attachments/assets/c62b775b-3f8d-4474-bb6c-eba668f841ca

**Comment by GopiRajuMatta** [comment]
> Hi, some videos are h.265 encoded. What OS and browser are you using?

I am using Ubuntu, tried with both Firefox and Chrome browsers...

**Comment by GopiRajuMatta** [comment]
> Here are two new videos:
> editing.mp4
> editing-2.mp4

Thank you so much for sharing these two videos...

Here in the viewer, why scene and point cloud, they are not registered well, there is a shift. Even when I tried with my reconstructions as well, there is a shift or scale change.. 

Can you please give a light on this.

Thank you
Gopi

**Comment by yzslab** [comment]
> > Here are two new videos:
> > editing.mp4
> > editing-2.mp4
> 
> Thank you so much for sharing these two videos...
> 
> Here in the viewer, why scene and point cloud, they are not registered well, there is a shift/scale change. Even when I tried with my reconstructions as well, there is a shift or scale change..
> 
> Can you please give a light on this.
> 
> Thank you Gopi

The are rendered in different ways, so you will see that shift/scale change.

**Comment by GopiRajuMatta** [comment]
Thank you so much for your timely response...
