### ISSUE TITLE
Is there any plan to support the fisheye camera model?

### ISSUE THREAD

**Issue by Sugar55888** [yzslab/gaussian-splatting-lightning#40]

**Comment by yzslab** [comment]
No. But you can use the command 'colmap image_undistorter ...' convert to
PINHOLE model.

**Comment by Sugar55888** [comment]
@yzslab Thank you very much for you reply! Do you mean that after using colmap image_undistorter or cv2.undistort to convert fisheye images into undistorted images, we can use the perspective camera model to train them for 3D Gaussian splatting?

**Comment by yzslab** [comment]
Right!

**Comment by Sugar55888** [comment]
Thank you! I will try it!
