### ISSUE TITLE
When I run the Segment Any 3D Gaussians code I have out of memory error

### ISSUE THREAD

**Issue by soohyoen** [yzslab/gaussian-splatting-lightning#41]
Hi, I'm running your Segment Any 3D Gaussian code and I have a problem.
I was able to reduce memory by down_sampling the generate SAM Masks part in the original Segment Any 3D Gaussians official code,
The "cuda out of memory" error appears because it cannot be done here.

How can we solve this?

**Comment by yzslab** [comment]
Hi, sorry that I haven't added downsampling for the Segment Any 3D Gaussian of this repo yet.

**Comment by yzslab** [comment]
The SegAny3DGS here and the official one are identical. So I recommand you use the official one currently.
The web viewer is able to load the official code's trained model: 
```bash
python viewer.py \
    SegAnyGAussians/outputs/Truck \
    --vanilla_seganygs
```

**Comment by soohyoen** [comment]
@yzslab 

Thank you so much for your quick reply.
First, I solved the problem by down_sampling the image in colmap.
But how about segmenting in viewer and rendering .pt file?
And when I save it, is it possible in ply format, not .pt?

**Comment by yzslab** [comment]
It can not save as ply currently.

The pt file contains the query vectors:
https://github.com/yzslab/gaussian-splatting-lightning/blob/00e1c7dc5c46f2b3ee13f1eea7f95030f6a24227/internal/renderers/seganygs_renderer.py#L626-L633

Here is how the mask calculated:
https://github.com/yzslab/gaussian-splatting-lightning/blob/00e1c7dc5c46f2b3ee13f1eea7f95030f6a24227/internal/renderers/seganygs_renderer.py#L444-L452

Some extra codes are required for pruning the Gaussians according to the
mask.

**Comment by soohyoen** [comment]
Thank you so much~!!

**Comment by soohyoen** [comment]
@yzslab 
Does masks capture location information?

**Comment by yzslab** [comment]
> @yzslab Does masks contain location information?

No. Mask is a boolean tensor. But you can get the locations in this way: `mask_xyz = xyz[mask]`.

**Comment by soohyoen** [comment]
> > @yzslab Does masks contain location information?
> 
> No. Mask is a boolean tensor. But you can get the locations in this way: `mask_xyz = xyz[mask]`, where `xyz` is the tensor containing locations of all the 3D Gaussians.

How do I write additional code to get mask_xyz like you said?

I'm a beginner, so I'm not used to it

**Comment by yzslab** [comment]
> > > @yzslab Does masks contain location information?
> > 
> > 
> > No. Mask is a boolean tensor. But you can get the locations in this way: `mask_xyz = xyz[mask]`, where `xyz` is the tensor containing locations of all the 3D Gaussians.
> 
> How do I write additional code to get mask_xyz like you said?
> 
> I'm a beginner, so I'm not used to it

Try this https://github.com/yzslab/gaussian-splatting-lightning/blob/main/utils/prune_by_segany_mask.py:
```bash
python utils/prune_by_segany_mask.py \
    --model ply_file_OR_ckpt_file \
    --mask segments/Truck.pt \
    --output pruned-Truck.ply
```

**Comment by soohyoen** [comment]
@yzslab 

That's amazing! This works really well! 

But I can't seem to map the color information, can you solve this? 
Sorry for the stupid questions that follow

**Comment by yzslab** [comment]
> @yzslab
> 
> That's amazing! This works really well!
> 
> But I can't seem to map the color information, can you solve this? Sorry for the stupid questions that follow

What's the "map the color information" you mentioned?

**Comment by soohyoen** [comment]
@yzslab 
If you run the code you suggested, the point cloud comes out in black and white. Maybe I didn't inherit the color information of the original point cloud.

**Comment by yzslab** [comment]
This is expected since the colors are not simply RGB but SHs. The colors
can only be shown correctly by 3DGS rasterizer, e.g. the web viewer of this
repo.

**Comment by yzslab** [comment]
> @yzslab If I run the code you suggested, the point cloud comes out in black and white. Maybe I didn't inherit the color information of the original point cloud.

If you really need ply with RGB colors, add a argument `with_colors=True` to the `save_to_ply(...)` in `utils/prune_by_segany_mask.py#L22`:
```diff
Index: utils/prune_by_segany_mask.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/utils/prune_by_segany_mask.py b/utils/prune_by_segany_mask.py
--- a/utils/prune_by_segany_mask.py	(revision 0ff87a4b2d26e927bdfc8b1da64e25775278d9c3)
+++ b/utils/prune_by_segany_mask.py	(date 1722408642510)
@@ -19,5 +19,5 @@
 mask = torch.load(args.mask, map_location="cpu")["mask"]
 
 properties = {key: value[mask] for key, value in model.properties.items()}
-GaussianPlyUtils.load_from_model_properties(properties).to_ply_format().save_to_ply(args.output)
+GaussianPlyUtils.load_from_model_properties(properties).to_ply_format().save_to_ply(args.output, with_colors=True)
 print(f"Saved to '{args.output}'")

```

**Comment by soohyoen** [comment]
@yzslab 
You really are a genius!
I did a lot of things thanks to you!

**Comment by soohyoen** [comment]
@yzslab 
I want to ask you a question again.
If you save the point cloud in this way, the color will be saved a little darker.
Can you tell me how to solve this problem?

![Monosnap Viser 🔊 2024-09-30 14-13-11](https://github.com/user-attachments/assets/cb853d92-9151-4264-a7bd-3907859cd4b3)

![Monosnap Viser 🔊 2024-09-30 14-13-23](https://github.com/user-attachments/assets/6c0f934c-25d4-418e-9008-49346e69ced7)
