### ISSUE TITLE
Where is the Decomposing scale??

### ISSUE THREAD

**Issue by soohyoen** [yzslab/gaussian-splatting-lightning#42]
![캡처](https://github.com/user-attachments/assets/dc979550-89c3-4c46-8b6b-a271fb85be22)

There's something in the original paper that can be broken down into sub-parts by decomposing, where can I find it in this code?

**Comment by yzslab** [comment]
This should be clustering: https://github.com/yzslab/gaussian-splatting-lightning/blob/6ea879e1ff86f18574e03d98fa67928ef1e61feb/internal/renderers/seganygs_renderer.py#L219-L221

**Comment by soohyoen** [comment]
@yzslab 
Thank you for your reply.
How do I write the code to control the scale?

**Comment by yzslab** [comment]
> @yzslab Thank you for your reply. How do I write the code to control the scale?

Here is the code calculating the `scale_conditioned_semantic_features` required by `SegAnyGSUtils.cluster_3d_as_dict`:
https://github.com/yzslab/gaussian-splatting-lightning/blob/6ea879e1ff86f18574e03d98fa67928ef1e61feb/internal/renderers/seganygs_renderer.py#L258-L264

**Comment by soohyoen** [comment]
@yzslab 
I'm so grateful and sorry that I got a lot of help from you.
I'm really sorry, but I'm a beginner so I don't know how to apply it..
Can you show me the example code?

**Comment by yzslab** [comment]
> @yzslab I'm so grateful and sorry that I got a lot of help from you. I'm really sorry, but I'm a beginner so I don't know how to apply it.. Can you show me the example code?

The [internal/renderers/seganygs_renderer.py](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/internal/renderers/seganygs_renderer.py) is a complete example already.
When you updating the scale value on the web viewer, the `scale_conditioned_semantic_features` will be updated too by the `update_scale_conditioned_features()`.
I recommand you to use a debugger and set break points, and then run the code step by step to understand how they are invoked.
