### ISSUE TITLE
Vast Gaussian module isn't uptodate with the rest of the codebase and OOM errors from Light Gaussian

### ISSUE THREAD

**Issue by MatthewDZane** [yzslab/gaussian-splatting-lightning#43]
Hi yzslab - Thanks for all the work. When I updated the code to use Vanilla Gaussian instead of BasicGaussan and then tried running the partition_light_gaussian_pruning I got "CUDA out of memory. Tried to allocate 15.64 GiB. GPU"

**Comment by yzslab** [comment]
Hi, it is indeed not up-to-date, since I made a refactor recently. I will take a look soon.

**Comment by yzslab** [comment]
Hi, pull the latest version and try again, it should work now.

**Comment by MatthewDZane** [comment]
Thank you @yzslab. I am having issues with merge_partitions now. I am getting this error:
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (250973x96 and 123x64)

Traceback (most recent call last):
  File "<unknown>", line 31, in <module>
    pruned_gaussian_model = get_pruned_gaussian_model(image_list, ckpt, is_in_partition)
  File "<unknown>", line 68, in <unknown>
    rgb_offset = embedding_network(input_tensor)
  File "~/Grendel-GS/training/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/Grendel-GS/training/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/Grendel-GS/gaussian-splatting-lightning/internal/utils/network_factory.py", line 18, in forward
    return self.output_layers(input)
  File "~/Grendel-GS/training/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (250973x96 and 123x64)
`

**Comment by earth-bass** [comment]
I haven't changed anything in the merge notebook.

**Comment by yzslab** [comment]
Hi, would you mind sending you ckpt to me for debugging?
This is my ema: ***@***.***

**Comment by MatthewDZane** [comment]
Sent it

**Comment by yzslab** [comment]
> Sent it

Received. I will take a look soon.

**Comment by yzslab** [comment]
> Sent it

I know what happened. You used `AppearanceEmbeddingRenderer` with `is_view_dependent=True`, while the I wrote the notebook in view indenpendent mode.
I will try to fix it.

**Comment by yzslab** [comment]
> Sent it

Hi, pull the latest version and try again.
