### ISSUE TITLE
Resolution decreases during rendering

### ISSUE THREAD

**Issue by smart4654154** [yzslab/gaussian-splatting-lightning#44]
Resolution decreases during rendering
Thank you very much, I encountered a bug while using the CityGaussian viewer.
This viewer is based on VISER.  I set the resolution to 1920, the photo quality to 100, and the moving resolution to 1920, the photo quality to 100.
1.During my movement, there was a noticeable decrease in resolution. When I finished moving and stopped pressing the keyboard, the rendering result suddenly became clear. 
For example ,from 28 seconds to 31 seconds in the video. This phenomenon is abnormal, theoretically the resolution should remain unchanged when moving.
2.When I finish moving and no longer press the keyboard, the rendering result is unclear. 
For example ,within 1 minute and 38 seconds of the video and beyond. This phenomenon is abnormal, theoretically the resolution should remain unchanged after the movement is completed.
Note: At other times, the resolution remains unchanged after the movement ends.
I'm not sure if this is a bug in Viser or GSPlat, can you help me? thank you.

the vedio:https://www.youtube.com/watch?v=KvWrNXg3BeA

**Comment by yzslab** [comment]
This issue looks solved in CityGaussian's repo. So close it now.
