### ISSUE TITLE
Questions regarding appearance model

### ISSUE THREAD

**Issue by hardikdava** [yzslab/gaussian-splatting-lightning#45]
Hello @yzslab , if I have trained a Gaussian splatting model with appearance model. I have following question. 

- do I need a MLP renderer while testing or viewing time? 
- How can I view trained model to web browser without GPU device?

Thanks in advance.

**Comment by yzslab** [comment]
Hi,
* Yes
* Use [utils/fuse_appearance_embeddings_into_shs_dc.py](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/utils/fuse_appearance_embeddings_into_shs_dc.py): `python utils/fuse_appearance_embeddings_into_shs_dc.py YOUR_TRAINED_MODEL_DIR`, then you will get a checkpoint whthout MLP requirement

**Comment by yzslab** [comment]
> Hi,
> 
> * Yes
> * Use [utils/fuse_appearance_embeddings_into_shs_dc.py](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/utils/fuse_appearance_embeddings_into_shs_dc.py): `python utils/fuse_appearance_embeddings_into_shs_dc.py YOUR_TRAINED_MODEL_DIR`, then you will get a checkpoint whthout MLP requirement

Besides, after removing the MLP using `utils/fuse_appearance_embeddings_into_shs_dc.py`, you will not be able to change the appearance.

**Comment by hardikdava** [comment]
@yzslab Thanks for the reply. 


> Besides, after removing the MLP using `utils/fuse_appearance_embeddings_into_shs_dc.py`, you will not be able to change the appearance.

Is it possible to apply appearance based on selected group or any other way during this conversion?

**Comment by yzslab** [comment]
> @yzslab Thanks for the reply.
> 
> > Besides, after removing the MLP using `utils/fuse_appearance_embeddings_into_shs_dc.py`, you will not be able to change the appearance.
> 
> Is it possible to apply appearance based on selected group or any other way during this conversion?

Of course, you can start implementing your method based on `utils/fuse_appearance_embeddings_into_shs_dc.py`.

**Comment by hardikdava** [comment]
Thanks for the replies. I will try it out.

**Comment by hardikdava** [comment]
@yzslab hey, just noticed that once the model is exported using `utils/ckpt2ply.py` script, all `feature_rest` data is missing in converted ply.

**Comment by yzslab** [comment]
> @yzslab hey, just noticed that once the model is exported using `utils/ckpt2ply.py` script, all `feature_rest` data is missing in converted ply.

This is expected, because I do not think other viewers are able to utilize it.

**Comment by yzslab** [comment]
> @yzslab hey, just noticed that once the model is exported using `utils/ckpt2ply.py` script, all `feature_rest` data is missing in converted ply.

Oh, you are talking `feature_rest`, not appearance features. I will take a look. Thanks.

**Comment by hardikdava** [comment]
@yzslab I think `feature_rest` is not saved in ckpt file itself. Hence missing in ply.

**Comment by yzslab** [comment]
> @yzslab I think `feature_rest` is not saved in ckpt file itself. Hence missing in ply.

Such a situation will not happen because `feature_rest` are stored in the same way as others.
I indeed found a bug in `ckpt2ply.py` just now, but looks like it will not drop `feature_rest`.
What is the config file are you using? Does it contain `sh_degree: 0` like [this one](https://github.com/yzslab/gaussian-splatting-lightning/blob/87beaf9b685f51cc49ae2477e114eb23fa86732b/configs/appearance_embedding_renderer/view_dependent.yaml#L5)?

**Comment by hardikdava** [comment]
@yzslab Oh, yeah. it has `sh_degree=0`. I am using `configs/appearance_embedding_renderer/view_dependent.yaml`

**Comment by yzslab** [comment]
> @yzslab Oh, yeah. it has `sh_degree=0`. I am using `configs/appearance_embedding_renderer/view_dependent.yaml`

That is why your ply does not contain `features_rest`.

**Comment by hardikdava** [comment]
@yzslab what was the reason behind putting `sh_degree=0` for training specially for appearance modeling.

**Comment by yzslab** [comment]
> @yzslab what was the reason behind putting `sh_degree=0` for training specially for appearance modeling.

The view dependent effects are represented by MLP in that config file. It looks meanless to use both the high SH degrees and MLP to do the same thing.
