### ISSUE TITLE
非常好的作品

### ISSUE THREAD

**Issue by chenqi13814529300** [yzslab/gaussian-splatting-lightning#47]
几个月前就发现这个项目了，但是一直没有跑，今天静下心来看看文档，内容真的很具体，很棒。还要时刻紧跟原作者更新的一些代码，这个工作量真的很大，竟然是3个人完成的，只能佩服。

**Comment by chenqi13814529300** [comment]
![image](https://github.com/user-attachments/assets/8a337bd6-b224-4bb4-963f-60854a088383)
![image](https://github.com/user-attachments/assets/5717bc77-3812-48ac-a2a4-de0000212613)
我想使用2.18. Depth Regularization with [Depth Anything V2](https://depth-anything-v2.github.io/)

**Comment by chenqi13814529300** [comment]
在测试2.18之前，2.12是可以测试的

**Comment by chenqi13814529300** [comment]
我问题解决了，我发现深度图生成的目录不在data2下面，居然在E盘的根目录下。我是window电脑，这个bug反馈一下

**Comment by yzslab** [comment]
> 我问题解决了，我发现深度图生成的目录不在data2下面，居然在E盘的根目录下。我是window电脑，这个bug反馈一下 ![image](https://private-user-images.githubusercontent.com/59059403/364205741-76b3f068-9adf-4ec0-bc7e-d360a68839e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjUyNzIsIm5iZiI6MTcyNTQyNDk3MiwicGF0aCI6Ii81OTA1OTQwMy8zNjQyMDU3NDEtNzZiM2YwNjgtOWFkZi00ZWMwLWJjN2UtZDM2MGE2ODgzOWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA0NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZmRlZjBkYzBiODRlYzQwZjgwMDM3OTk1OTg3ODJkZDVjZGM4ZDA3MDNhOTU0MzBjZWMwZGM1NzI5MzZjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sk5dB96MenxyxJVwRWXnYRXQQUDSeKdJaYnJHD2c_aA)

Thanks. I will take a look.

**Comment by yzslab** [comment]
> 我问题解决了，我发现深度图生成的目录不在data2下面，居然在E盘的根目录下。我是window电脑，这个bug反馈一下

The latest version should work correctly on Windows now.


> 竟然是3个人完成的

In fact, I did almost all alone: https://github.com/yzslab/gaussian-splatting-lightning/graphs/contributors

**Comment by chenqi13814529300** [comment]
真的太厉害了，真的离谱啊
