### ISSUE TITLE
Model training without CLI

### ISSUE THREAD

**Issue by hardikdava** [yzslab/gaussian-splatting-lightning#52]
@yzslab Is it possible to train a model without using CLI mode? If yes, how can it be used?

**Comment by yzslab** [comment]
If you mean starting training without CLI, no.
If you want to use the web viewer during training, simply add the option `--viewer` to `main.py`.

**Comment by hardikdava** [comment]
@yzslab I want to train a model using python interface. But that is not possible. If we want to do it then we have to use subprocess which is not a good idea.

**Comment by yzslab** [comment]
> @yzslab I want to train a model using python interface. But that is not possible. If we want to do it then we have to use subprocess which is not a good idea.

Maybe you can take a look at whether the LightningCLI used by this repo provides the interfaces you want, or skip LightningCLI and simply follow the PyTorch Lightning's guidance to start training.

**Comment by hardikdava** [comment]
Closed #53
