### ISSUE TITLE
Appearance variation result

### ISSUE THREAD

**Issue by hardikdava** [yzslab/gaussian-splatting-lightning#6]
Hey @yzslab , a great work. I see that the implementation support of appearance variation. Do you have any results? e.g. how much improvement and thoughts behind it.

**Comment by yzslab** [comment]
Only some a little bit experiments has been done. It simply use a MLP to adjust the white balance and gamma of the render image.
Here is a simple comparation: https://github.com/graphdeco-inria/gaussian-splatting/issues/95#issuecomment-1682107392

**Comment by hardikdava** [comment]
@yzslab Thank you for your reply. I got the idea.
