### ISSUE TITLE
The lambda_dist of 2DGS

### ISSUE THREAD

**Issue by vsfh** [yzslab/gaussian-splatting-lightning#63]
Maybe the lambda_dist of 2DGS should be set to 100 or 1000 with command line?

 Like the official repo did in:
https://github.com/hbb1/2d-gaussian-splatting/blob/19eb5f1e091a582e911b4282fe2832bac4c89f0f/scripts/tnt_eval.py#L25

**Comment by yzslab** [comment]
You can set it in this way: 
```
... main.py fit \
  --config --config configs/vanilla_2dgs.yaml \
  ... \
  --model.metric.lambda_dist THE_VALUE_YOU_WANT
```
