### ISSUE TITLE
import error for 4dgaussians viewer 

### ISSUE THREAD

**Issue by weihan1** [yzslab/gaussian-splatting-lightning#66]
Hello,

Thanks for the great work! I have encountered this issue:

ImportError: /scratch/ondemand28/weihanluo/miniconda3/envs/gspl/lib/python3.9/site-packages/diff_gaussian_rasterization/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb

when running python viewer.py <4dgs_output_dir>  --vanilla_gs4d 

I followed the instructions from the readme, my pytorch version is 2.0.1 with cuda 11.7 and pip install -e . ran successfully.
Any help would be greatly appreciated 🙏

**Comment by weihan1** [comment]
ok nvm solved, i basically had to remove the commit hash in the toml file prior to installation

**Comment by jin-sss** [comment]
Hello, I also encountered a similar issue. Could you please tell me how you resolved it? Thank you.
![QQ截图20241007170332](https://github.com/user-attachments/assets/92d1a768-497b-4036-8806-9b71a36e4f4c)

**Comment by weihan1** [comment]
what worked for me was removing the commit hashes in the toml file:

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["internal*", "utils*"]

[project]
name = "gaussian-splatting-lightning"
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "lightning[pytorch-extra]==2.0.9.post0",
    "pytorch-lightning==2.3.*",
    "splines==0.3.0",
    "plyfile==0.8.1",
    "tensorboard",
    "wandb",
    "tqdm",
    "viser==0.2.3",
    "opencv-python==4.10.*",
    "matplotlib",
    "mediapy==1.2.2",
    "diff-gaussian-rasterization @ git+https://github.com/graphdeco-inria/diff-gaussian-rasterization.git",
    "simple-knn @ git+https://gitlab.inria.fr/bkerbl/simple-knn.git"]

[project.scripts]
gs-fit = "internal.entrypoints.gspl:cli_fit"
gs-val = "internal.entrypoints.gspl:cli_val"
gs-test = "internal.entrypoints.gspl:cli_test"
gs-predict = "internal.entrypoints.gspl:cli_predict"

segany-fit = "internal.entrypoints.seganygs:cli_fit"
segany-val = "internal.entrypoints.seganygs:cli_val"
segany-test = "internal.entrypoints.seganygs:cli_test"
segany-predict = "internal.entrypoints.seganygs:cli_predict"

gs-viewer = "internal.entrypoints.viewer:cli"

**Comment by jin-sss** [comment]
Thank you for your response. I’m sorry, but this doesn’t help me. My original server was CUDA 11.5, and everything went smoothly when I switched to a server with CUDA 12.4. I still appreciate your reply.
