### ISSUE TITLE
Gaussian sphere size

### ISSUE THREAD

**Issue by chenqi13814529300** [yzslab/gaussian-splatting-lightning#67]
I hope the size of the generated Gaussian sphere is not too large (the longest dimension), and should be kept in a relatively small state. How should I modify the code?

**Comment by yzslab** [comment]
Which type of the sphere are you talking about? The size of the Gaussian or the background sphere?
If it is the former one, you need to add a regularization loss on the size vector.
About later one, take a look the parameters here: https://github.com/yzslab/gaussian-splatting-lightning/blob/7a062a33870cec9ae4de6e989d4a41a6b64cd538/internal/dataset.py#L271-L276

**Comment by chenqi13814529300** [comment]
Thank you for your answer！
