### ISSUE TITLE
Multi-View Training for Huge Improvement

### ISSUE THREAD

**Issue by xiaobiaodu** [yzslab/gaussian-splatting-lightning#68]
Hi

Thanks for your excellent work!
Here is a repository that provides a simple and effective multi-view training strategy for 3DGS and obtains huge Improvement around 1 dB PSNR. https://github.com/xiaobiaodu/MVGS
I guess it would make your repository more welcome.

Best,
Xiaobiao Du

**Comment by yzslab** [comment]
Thanks, I will take a look later.
