### ISSUE TITLE
Nerfstudio data format supports

### ISSUE THREAD

**Issue by mini-full** [yzslab/gaussian-splatting-lightning#69]
Hi, I am wondering if I can use a Apple ARKit based app (like polycam or nerfcapture) to collect data, since ARKit usually gives more accurate pose estimation.
In this case I do not have a colmap database, but a transforms.json can be read from the output of these apps.
My data format is like:
```
   |-images
   |-images_2
   |-images_4
   |-images_8
   transforms.json
```
And optionally a sparse pointcloud for initialization.

Is that possible to transform that into colmap data format? I did search the web but found no ready-to-use solution.

Thanks for your time.

**Comment by yzslab** [comment]
Converting to colmap is possible, you can implement it base on [utils/meganerf2colmap.py](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/utils/meganerf2colmap.py).

You can also try using the [`NGPDataParser`](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/internal/dataparsers/ngp_dataparser.py): `--data.parser internal.dataparsers.ngp_dataparser.NGP`.
However, you should make sure that all of the cameras in `transforms.json` are PINHOLE models, i.e. all the distortion coefficients are zero, and place the `points3D.ply` to the same directory as `transforms.json`, or you will get a sub-optimal result.

**Comment by mini-full** [comment]
Thank you for your kind response. I will try that later.
