### ISSUE TITLE
render from viser

### ISSUE THREAD

**Issue by antoinebio** [yzslab/gaussian-splatting-lightning#7]
Hello
I am trying to generate a render video from viser

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/768747b6-84c1-4857-ab6f-bc7c9a8dce4e)

but the process ends with that error

![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/30265851/f3416ddd-f40f-4ee3-8122-4faafd45198f)

is there any missing lib ?

**Comment by yzslab** [comment]
Ignore it.

**Comment by yzslab** [comment]
It won't affect the video generation.
