### ISSUE TITLE
Do not display content after running web viewer

### ISSUE THREAD

**Issue by chy2013920202** [yzslab/gaussian-splatting-lightning#70]
As shown in the picture
![image](https://github.com/user-attachments/assets/d3f4e895-5fed-4196-abfa-9fa3d28fea62)
![image](https://github.com/user-attachments/assets/0a2b3a4b-6362-479f-a852-7fd7dc48ce45)
Can someone tell me how to solve this? Do I need to deploy it to the server? I opened it directly under window11 http://localhost:8080/ . If you have a solution, thank you very much

**Comment by dongxiaozi** [comment]
Simply click on the blue URL to the right of HTTP, and it should jump to the web page and display it.

**Comment by chy2013920202** [comment]
> Simply click on the blue URL to the right of HTTP, and it should jump to the web page and display it.只需单击 HTTP 右侧的蓝色 URL，它就会跳转到网页并显示它。

I was like this from the beginning, but I couldn't even display the icon. It wasn't until I added my own IPv4 address that the icon appeared. I am trying to deploy it on Ubuntu.

**Comment by yzslab** [comment]
Press the F12, then switch to the console tab. Take a look what it reported.

**Comment by chy2013920202** [comment]
> Press the F12, then switch to the console tab. Take a look what it reported
hi， Hello, this is my console content. Do you have any questions? Thank you very much for your answer
![image](https://github.com/user-attachments/assets/16d9f901-6c1a-45c7-b49a-1b72e4ef386a)
![image](https://github.com/user-attachments/assets/ad22270b-5ff0-492f-ba97-ccdc85c481dd)

**Comment by yzslab** [comment]
> hi， Hello, this is my console content. Do you have any questions? Thank you very much for your answer

Not sure what happened.
Try using another port to see whether it works: start the viewer by `python viewer.py MODEL_PATH --port 7008`, then access `http://127.0.0.1:7008`

**Comment by chy2013920202** [comment]
> > hi， Hello, this is my console content. Do you have any questions? Thank you very much for your answer
> 
> Not sure what happened. Try using another port to see whether it works: start the viewer by `python viewer.py MODEL_PATH --port 7008`, then access `http://127.0.0.1:7008`

Thank you very much for your answer, but it doesn't seem to work. Is my output model different from yours?I am using the LEGO model from 4DGassians
![image](https://github.com/user-attachments/assets/eed61827-9547-4098-98fd-64f800984e19)
![image](https://github.com/user-attachments/assets/c54b2fb3-4d7d-4b9f-95bf-5b86f024bddd)

**Comment by yzslab** [comment]
> Thank you very much for your answer, but it doesn't seem to work. Is my output model different from yours?I am using the LEGO model from 4DGassians

Start the viewer with `--port 7008`, then try accessing via this URL: https://nsv.cslab.pro/viser-0.2.3/?websocket=ws://127.0.0.1:7008

**Comment by chy2013920202** [comment]
> > Thank you very much for your answer, but it doesn't seem to work. Is my output model different from yours?I am using the LEGO model from 4DGassians
> 
> Start the viewer normally, then try accessing via this URL: https://nsv.cslab.pro/viser-0.2.3/?websocket=ws://127.0.0.1:8080

omg， This can be used now, it is really important for a student who has just become a graduate student. Thank you very much for your work and help!!!

**Comment by chy2013920202** [comment]
Thank you very much for your help

**Comment by chy2013920202** [comment]
Thank you very much for your help

**Comment by chy2013920202** [comment]
Thank you very much for your help
