### ISSUE TITLE
depth anything estimate depth too slow

### ISSUE THREAD

**Issue by dongxiaozi** [yzslab/gaussian-splatting-lightning#71]
Hello, I am using depth anything with over 300 images, running: Python utils/estimate. PY data/images command, xFormers not available, and seems to have been loading the model for a long time, no response. Do you know why, is it because xFormers is not installed, i tried installing it, but it required a version of pytorch that conflicted with the package. Maybe it's the amount of images I'm processing?
![picture](https://github.com/user-attachments/assets/754bd9dd-93e7-4fe4-99df-87fec9dfafa7)

**Comment by dongxiaozi** [comment]
Sorry, I made a mistake in my expression. As shown in the picture, the path was created according to the tutorial: python utilities/estimate_dataset_depth. py /home/wangyi/han/dataset/. In dataset file, there are two folders processed with colmap: images and sparse.

**Comment by yzslab** [comment]
Hi, pull the latest commit then run again. See what it will reports.

**Comment by dongxiaozi** [comment]
Hello, thank you very much. The error message is: not an image with extension name ["JPG....]. Since the images in my dataset are in PNG format, adding this category resulted in successful execution.
