### ISSUE TITLE
Mesh Extraction Support for 2dgs

### ISSUE THREAD

**Issue by mini-full** [yzslab/gaussian-splatting-lightning#74]
Hi Author,

I am wondering do you provide mesh extraction support for 2dgs, if the data is not COLMAP format, i.e. using other data parsers to perform mesh extraction?

[https://github.com/hbb1/2d-gaussian-splatting?tab=readme-ov-file#testing](url)

**Comment by yzslab** [comment]
Hi, RGB only currently.
