### ISSUE TITLE
Taming GS Integration

### ISSUE THREAD

**Issue by alpergel** [yzslab/gaussian-splatting-lightning#81]
Hey @yzslab , are there any plans to integrate the drop in accelerations from TamingGS? Would you be interested in a PR for that?

**Comment by yzslab** [comment]
Hi, here is a simple workaround: https://github.com/yzslab/gaussian-splatting-lightning/tree/main/configs/taming_3dgs

**Comment by yzslab** [comment]
The gsplat v1 has the optimizations from Taming3DGS now, except the "Backpropagation with Per-Splat Parallelization".
Only about 1 minute slower than the vanilla Taming3DGS. 
Give it a try if you need: https://github.com/yzslab/gaussian-splatting-lightning?tab=readme-ov-file#221-taming-3dgs.

**Comment by alpergel** [comment]
Perfect thank you!
