### ISSUE TITLE
SpotLessSplats Metrics Error

### ISSUE THREAD

**Issue by alpergel** [yzslab/gaussian-splatting-lightning#90]
Hello, Im getting the following error: File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/alper1/code/Users/alper/gaussian-splatting-lightning/internal/metrics/spotless_metrics.py", line 145, in reset_shs_rest
    gaussian_model.update_properties(DensityControllerUtils.replace_tensors_to_optimizers({"shs_rest": gaussian_model.shs_rest}, pl_module.gaussian_optimizers))
AttributeError: type object 'Utils' has no attribute 'replace_tensors_to_optimizers'

The overall command is: python main.py fit --data.path ../chicago_video/ --model.save_ply true --config configs/taming_3dgs/rasterizer-fused_ssim-sparse_adam-aa.yaml --config configs/spot_less_splats/gsplat-cluster.yaml --data.parser.split_mode "reconstruction" --config configs/light_gaussian/custom-prune.yaml --data.image_on_cpu false  --data.num_workers 24 --float32_matmul_precision medium --trainer.check_val_every_n_epoch 100 --data.image_uint8 true --trainer.profiler=simple --n 6

**Comment by yzslab** [comment]
Hi, pull the latest version then try again, it should work now.
Besides, the `taming_3dgs/rasterizer-fused_ssim-sparse_adam-aa.yaml` can not work with `spot_less_splats/gsplat-cluster.yaml`. 
Both of them delcare different Renderer and Metrics. The later one will override the former.
