### ISSUE TITLE
Spot Less Splat + Appearance Model for Colmap?

### ISSUE THREAD

**Issue by alpergel** [yzslab/gaussian-splatting-lightning#93]
Hey @yzslab would it be possible to do this combo with colmap? I saw this is a thing for phototourism dataset

**Comment by yzslab** [comment]
Of course.
SImply replace the 
```yaml
class_path: PhotoTourism
``` 
with 
```yaml
class_path: internal.dataparsers.spotless_colmap_dataparser.SpotLessColmap
```
, and do not forget the `cluster: true` if you are using cluster mode.

**Comment by alpergel** [comment]
Perfect thank you!
