### ISSUE TITLE
Spiky Gaussian Output

### ISSUE THREAD

**Issue by alpergel** [yzslab/gaussian-splatting-lightning#94]
Hey @yzslab sorry for the continual questions. Im getting results like the below whenever I use gspl. Its the same across different configs. Im using VGGsfm for the preprocessing component, do you have any suggestions on why this could be happening? 
![Screenshot 2024-12-11 120341](https://github.com/user-attachments/assets/989a85a3-8343-4fa9-bb39-8806ede9fb75)

**Comment by yzslab** [comment]
Does it render correctly when using [`viewer.py`](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/viewer.py)?
How many training images do you have? If only 18, it is not enough to have a well-generalizable reconstruction.

**Comment by earth-bass** [comment]
I am also seeing a similar issue where when I drop a model that I have trained with repo into a web viewer like playcanvas supersplat or three js, I see similar thin long spikes and they don't look like splats.

**Comment by yzslab** [comment]
> I am also seeing a similar issue where when I drop a model that I have trained with repo into a web viewer like playcanvas supersplat or three js, I see similar thin long spikes and they don't look like splats. The datasets I am training on are 100s of images, so it's not the size of the dataset for me. It looks better on the viewer.py than on the web viewer.

Which config file did you use to create this reconstruction?

**Comment by earth-bass** [comment]
`model:
  random_background: true
  gaussian:
    class_path: internal.models.appearance_feature_gaussian.AppearanceFeatureGaussian
    init_args:
      sh_degree: 3
      appearance_feature_dims: 64
      optimization:
        appearance_feature_lr_init: 2e-3
  renderer:
    class_path: internal.renderers.gsplat_appearance_embedding_renderer.GSplatAppearanceEmbeddingRenderer
    init_args:
      model:
        is_view_dependent: false
      optimization:
        warm_up: 1000
      tile_based_culling: true
  metric:
    fused_ssim: true
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  parser:
    class_path: Colmap
    init_args:
      split_mode: "reconstruction"
     `

**Comment by alpergel** [comment]
Very similar config on my end

**Comment by earth-bass** [comment]
Oh I think it might be the antialias. I will test and get back to you

**Comment by alpergel** [comment]
How would we disable AA?

**Comment by earth-bass** [comment]
It's an option in GSplatAppearanceEmbeddingRenderer, you can look the file up and disable there or disable it in the config.

**Comment by yzslab** [comment]
> How would we disable AA?

`--model.renderer.anti_aliased false`

**Comment by alpergel** [comment]
@yzslab btw would you be interested in a Vggsfm automatic script integration? Happy to do that, your repo has been a huge help

**Comment by yzslab** [comment]
> would you be interested in a Vggsfm automatic script integration?

Maybe later.

**Comment by alpergel** [comment]
@earth-bass whats the benefit of the random background?

**Comment by alpergel** [comment]
The AA didnt fix it for me btw

**Comment by earth-bass** [comment]
> @earth-bass whats the benefit of the random background?

Discourages relying on the black background for some of the shadows or black adjacent things, it will put actual splats in there instead.

**Comment by yzslab** [comment]
Here is the Train scene from Tanks and Temple that trained with appearance model just now:
https://www.dropbox.com/scl/fo/h0as3u3evwj6ec08e4cn1/AAWCifQSaEszaIcDF7XJsl4?rlkey=z3r40k85oauyis68hiwsvhtrv&st=8hstfvpq&dl=0

Does this one have the issue you mentioned on the WebGL viewer?

I tried loading it with [mkkellogg/GaussianSplats3D](https://github.com/mkkellogg/GaussianSplats3D) and looks fine.
This is my settings:
![image](https://github.com/user-attachments/assets/5cbcd65c-855e-414c-896d-e7d033645664)
The up direction is `-0.0233,-0.9837,0.178`.

**Comment by alpergel** [comment]
That looks fine to me. Should we always run the fusing script even if we train with the view independent config? I dont understand why its not working for us.

**Comment by yzslab** [comment]
> I dont understand why its not working for us.

Here are the steps I created that ply file:
1. Train: `python main.py fit ... -n Train -v appearance-normalized-1213`
2. Fusing: `python utils/fuse_appearance_embeddings_into_shs_dc.py outputs/Train/appearance-normalized-1213`
3. Converting: `python utils/ckpt2ply.py outputs/Train/appearance-normalized-1213/checkpoints/fused.ckpt`

In the 3rd step, you must specify the path of the `fused.ckpt`, or it will automatically choose the non-fused one. I am not sure if you are aware of this.

**Comment by alpergel** [comment]
Could it be that im training with the save ply argument rather than converting checkpoint to ply after?

**Comment by alpergel** [comment]
> > Should we always run the fusing script even if we train with the view independent config?
> 
> Whether view dependent or not, fusing is required before converting to ply as long as you enable AppearanceModel.

I think this should be noted in the ReadMe if so, the current wording does not indicate that.

**Comment by yzslab** [comment]
> Could it be that im training with the save ply argument rather than converting checkpoint to ply after?

No.

**Comment by yzslab** [comment]
> Could it be that im training with the save ply argument rather than converting checkpoint to ply after?

You have to manually run the 2nd and 3rd steps. The `--model.save_ply` can not work correctly when using AppearanceModel.
