### ISSUE TITLE
Convention of the Camera class

### ISSUE THREAD

**Issue by kxwangzju** [yzslab/gaussian-splatting-lightning#97]
Dear Author,

I am wondering how you define the convention of the Camera class for rendering. In the `Camera` class, R and T are initialized as part of `w2c` matrix. And w2c matrix seems to be the inverse of the c2w matrix(flipped y and z axis in order to convert to OpenGL frame?).

What should I do to initialize the Camera if I have the (x,y,z) position of the camera in the world frame, and a rotation matrix describing each axis of the camera in the world frame, with OpenGL convention? I tried several transforms, but I cannot get the desired render outputs.

I noticed that in https://github.com/yzslab/gaussian-splatting-lightning/blob/a4123b4f368bc8f64c25332e8929922786e948d5/internal/utils/graphics_utils.py#L106 the translation is not changed with the rotation matrix (I believe this part of code is from vanilla 3dgs, but seems that it's not a real `w2c` matrix?)

Thank you for your time.

**Comment by yzslab** [comment]
The function `getWorld2View` is not used here.

The convention is the same as the vanilla 3DGS, i.e. the COLMAP/OpenCV convention: the X axis points to the right, the Y axis to the bottom, and the Z axis to the front as seen from the image.



> What should I do to initialize the Camera if I have the (x,y,z) position of the camera in the world frame, and a rotation matrix describing each axis of the camera in the world frame, with OpenGL convention?

Let's denote your position as $\textbf{T}$ and rotation as $\textbf{R}$. Therefore, you have the camera-to-world transformation:
```math
\mathbb{T}_{c2w}
=
\begin{bmatrix}
\mathbb{R}  & \mathbb{T} \\
\mathbb{0}  & \mathbb{1}
\end{bmatrix}
```

Then convert it to the OpenCV convention by flipping the Y and Z axis:
```math
\mathbb{T}_{\text{c2w\_colmap}}
 = 
\begin{bmatrix}
\mathbb{R}  & \mathbb{T} \\
\mathbb{0}  & \mathbb{1}
\end{bmatrix}
\begin{bmatrix}
1  & 0 & 0 & 0 \\
0  & -1 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 0 & 0 & 1 \\ 
\end{bmatrix}
```

Then the world-to-camera transformation is:
```math
T_{w2c} = {\mathbb{T}_{\text{c2w\_colmap}}}^{-1}
```

You can find the code here: https://github.com/yzslab/gaussian-splatting-lightning/blob/a4123b4f368bc8f64c25332e8929922786e948d5/internal/dataparsers/blender_dataparser.py#L50-L56

**Comment by kxwangzju** [comment]
Thank you for your detailed answer. I will check that

**Comment by kxwangzju** [comment]
Hi I have another question. When I load a gs point cloud using `viewer.py`, in the scene tree there're three attributes, `WorldAxes`, `Camera Orientation` and `Camera Orientation Transformation`, what does the `Camera Orientation` mean here? I didn't load any camera.

**Comment by yzslab** [comment]
It is the orientation of the viewer's camera, used to set the up direction.

**Comment by kxwangzju** [comment]
But seems like it doesn't move when I am dragging to change the viewpoint

**Comment by yzslab** [comment]
It only changes the up direction. Take a look at the video in the FAQ of
the README.

**Comment by kxwangzju** [comment]
Got it! Thanks :)
