### ISSUE TITLE
viewer.py script gets nearby objects being blurred when moving forward by pressing W

### ISSUE THREAD

**Issue by a11enL** [yzslab/gaussian-splatting-lightning#98]
Thanks for your great work,  viewer.py script gets nearby objects being blurred when moving forward by pressing W,  and also the rendered video is the same situation. ( the same with render.py script)

(This is a copied question from Viser' project issues, https://github.com/nerfstudio-project/viser/issues/360 )

https://github.com/user-attachments/assets/329bbda8-aa11-4def-be3d-9d6a5fde2457

**Comment by yzslab** [comment]
Hi, please provide the command that you use to start the viewer.

**Comment by a11enL** [comment]
Hi, my command :

python3 ../gslightning-0.10.1/viewer.py --port 8082 --enable_transform ../exports/test123/truck.ply

**Comment by yzslab** [comment]
Using gsplat should solve your problem. Issue #95 mentioned how to use it.

**Comment by a11enL** [comment]
Thanks you! it should ok now, just my package version problem (it seems version 0.10.1 is still not compatible with gsplat-1.4.0), I will fix it myself.

------------------------------
CUDA_VISIBLE_DEVICES=2 python3 ../gslightning-0.10.1/viewer.py --gsplat --port 8082 --enable_transform ../exports/test123/truck.ply
load model from ../exports/test123/truck.ply
Traceback (most recent call last):
  File "/home/ubuntu/gslightning-0.10.1/../gslightning-0.10.1/viewer.py", line 4, in <module>
    cli()
  File "/home/ubuntu/gslightning-0.10.1/internal/entrypoints/viewer.py", line 64, in cli 
    viewer = Viewer(**viewer_init_args)
  File "/home/ubuntu/gslightning-0.10.1/internal/viewer/viewer.py", line 132, in __init__
    model, renderer, training_output_base_dir, dataset_type, self.checkpoint = self._load_model_from_file(load_from)
  File "/home/ubuntu/gslightning-0.10.1/internal/viewer/viewer.py", line 469, in _load_model_from_file
    from internal.renderers.gsplat_renderer import GSPlatRenderer
  File "/home/ubuntu/gslightning-0.10.1/internal/renderers/gsplat_renderer.py", line 2, in <module>
    from gsplat import project_gaussians
ImportError: cannot import name 'project_gaussians' from 'gsplat' (/home/ubuntu/gsplat-1.4.0/gsplat/__init__.py)

**Comment by yzslab** [comment]
Did you install my modified v1?

**Comment by yzslab** [comment]
Please follow the README of this repo to setup the gsplat v1.

**Comment by a11enL** [comment]
Thank you, I will try them and I would like to run this in a single python environment (keep gsplat-1.4.0 first).

**Comment by yzslab** [comment]
Another option is to reduce near culling of the diff-gaussian-rasterization [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/auxiliary.h#L154), then re-compile it.
Besides, if you decide to use my modified v1 later, remember to pull the latest commit, or you will get suboptimal results on ply files.

**Comment by a11enL** [comment]
Finally I switched  back to diff-gaussian-rasterization and work, changed:

p_view.z <= 0.2f
->
p_view.z <= 0.001f 


https://github.com/user-attachments/assets/1de62138-9906-4c65-b56f-2339d42ad7c4
